version: '3.8'
services:

  betstats-1:
    image: gumball7/betstats
    container_name: betstats-1
    ports:
      - "4000:4000"
    environment:
      - SELF_PORT=4000
      - DB_URL=events_db
      - DB_PORT=5432
    depends_on:
      - events_db
      - redis
  
  betstats-2:
    image: gumball7/betstats
    container_name: betstats-2
    ports:
      - "4001:4001"
    environment:
      - SELF_PORT=4001
      - DB_URL=events_db
      - DB_PORT=5432
    depends_on:
      - events_db
      - redis

  betstats-3:
    image: gumball7/betstats
    container_name: betstats-3
    ports:
      - "4002:4002"
    environment:
      - SELF_PORT=4002
      - DB_URL=events_db
      - DB_PORT=5432
    depends_on:
      - events_db
      - redis

  youtubeservice-1:
    image: gumball7/youtubeservice
    container_name: youtubeservice-1
    ports:
      - "5000:5000"
    environment:
      - SELF_PORT=5000
      - DB_URL=videos_db
      - DB_PORT=5432
    depends_on:
      - videos_db
      - redis
  
  youtubeservice-2:
    image: gumball7/youtubeservice
    container_name: youtubeservice-2
    ports:
      - "5001:5001"
    environment:
      - SELF_PORT=5001
      - DB_URL=videos_db
      - DB_PORT=5432
    depends_on:
      - videos_db
      - redis

  youtubeservice-3:
    image: gumball7/youtubeservice
    container_name: youtubeservice-3
    ports:
      - "5002:5002"
    environment:
      - SELF_PORT=5002
      - DB_URL=videos_db
      - DB_PORT=5432
    depends_on:
      - videos_db
      - redis

  gateway:
    image: gumball7/gateway
    container_name: gateway
    ports:
      - "7000:7000"
    environment:
      - REQUEST_TIMEOUT=6s
      - REDIS_HOST=redis
      - TIME_WINDOW=60
      - MAX_TASKS=100

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  events_db:
    image: postgres:latest
    container_name: events_db
    environment:
      POSTGRES_USER: ana
      POSTGRES_PASSWORD: ana
      POSTGRES_DB: events
    volumes:
      - events-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  videos_db:
    image: postgres:latest
    container_name: videos_db
    environment:
      POSTGRES_USER: ana
      POSTGRES_PASSWORD: ana
      POSTGRES_DB: videos
    volumes:
      - videos-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards

volumes:
  redis-data:
  events-data:
  videos-data: