global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gateway:6000'] 
        labels:
          application: 'Gateway'

  - job_name: 'betstats'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['betstats-1:4000']  
        labels:
          application: 'BetStats'

  - job_name: 'youtubeservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['youtubeservice-1:5000'] 
        labels:
          application: 'YoutubeIntegratorService'
